server:
  port: 10085
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10085/eureka
    register-with-eureka: false
    fetch-registry: false
